# Generated by Django 4.2.20 on 2026-06-30 11:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the company",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Company name", max_length=255, unique=True)),
                ("legal_name", models.CharField(blank=True, help_text="Legal/registered company name", max_length=255)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("hq", "Headquarters"),
                            ("sub", "Subsidiary"),
                            ("branch", "Branch"),
                            ("showroom", "Showroom"),
                            ("warehouse", "Warehouse"),
                        ],
                        default="hq",
                        help_text="Type of company/entity",
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("textile", "Textile Trading"),
                            ("garment", "Garment Trading"),
                            ("manufacturing", "Manufacturing"),
                            ("retail", "Retail"),
                            ("wholesale", "Wholesale"),
                            ("ecommerce", "E-commerce"),
                        ],
                        default="textile",
                        help_text="Primary industry",
                        max_length=20,
                    ),
                ),
                ("tax_id", models.CharField(blank=True, help_text="Tax identification number", max_length=50)),
                (
                    "commercial_register",
                    models.CharField(blank=True, help_text="Commercial registration number", max_length=50),
                ),
                ("registration_date", models.DateField(blank=True, help_text="Date of registration", null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid", regex="^\\+?\\d{7,15}$"
                            )
                        ],
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile number must be valid", regex="^\\+?\\d{7,15}$"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, help_text="Company email address", max_length=254)),
                ("website", models.URLField(blank=True, help_text="Company website")),
                ("address", models.TextField(blank=True, help_text="Full address")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, help_text="State/Province", max_length=100)),
                ("country", models.CharField(default="Egypt", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("currency", models.CharField(default="EGP", help_text="Primary currency (ISO code)", max_length=3)),
                ("fiscal_year_start", models.IntegerField(default=7, help_text="Starting month of fiscal year (1-12)")),
                ("fiscal_year_end", models.IntegerField(default=6, help_text="Ending month of fiscal year (1-12)")),
                ("timezone", models.CharField(default="Africa/Cairo", max_length=50)),
                (
                    "date_format",
                    models.CharField(default="d/m/Y", help_text="Date format (PHP date format)", max_length=20),
                ),
                (
                    "time_format",
                    models.CharField(default="H:i:s", help_text="Time format (PHP time format)", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False, help_text="Whether the company has been verified")),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_expires_at",
                    models.DateTimeField(blank=True, help_text="When the subscription expires", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "common_companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Feature name", max_length=100)),
                ("code", models.CharField(help_text="Unique feature code", max_length=50, unique=True)),
                ("module", models.CharField(help_text="Module that owns this feature", max_length=50)),
                ("description", models.TextField(blank=True, help_text="Feature description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("beta", "Beta"),
                            ("deprecated", "Deprecated"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="enabled",
                        help_text="Current status of the feature",
                        max_length=20,
                    ),
                ),
                ("require_staff", models.BooleanField(default=False, help_text="Only staff users can access")),
                ("require_superuser", models.BooleanField(default=False, help_text="Only superusers can access")),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=100, help_text="Percentage of users to enable this feature for (0-100)"
                    ),
                ),
                (
                    "environments",
                    models.JSONField(default=list, help_text="List of environments where this feature is enabled"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the feature becomes available"
                    ),
                ),
                ("valid_until", models.DateTimeField(blank=True, help_text="When the feature expires", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "require_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions required to access",
                        related_name="feature_flags",
                        to="authentication.enterprisepermission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "db_table": "common_feature_flags",
                "ordering": ["module", "name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the branch",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Branch name", max_length=255)),
                ("code", models.CharField(help_text="Branch code (unique within company)", max_length=20)),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("hq", "Headquarters"),
                            ("store", "Store"),
                            ("warehouse", "Warehouse"),
                            ("office", "Office"),
                            ("showroom", "Showroom"),
                            ("factory", "Factory"),
                        ],
                        default="store",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid", regex="^\\+?\\d{7,15}$"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, help_text="Branch email address", max_length=254)),
                ("address", models.TextField(blank=True, help_text="Branch address")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Egypt", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_headquarters", models.BooleanField(default=False, help_text="Whether this is the headquarters")),
                ("opening_time", models.TimeField(blank=True, help_text="Regular opening time", null=True)),
                ("closing_time", models.TimeField(blank=True, help_text="Regular closing time", null=True)),
                ("timezone", models.CharField(default="Africa/Cairo", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that this branch belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="common.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_branches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent branch if this is a sub-branch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_branches",
                        to="common.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "common_branches",
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="UserCompany",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Whether this is the user's default company"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time when user was assigned to this company"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that the user has access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_companies",
                        to="common.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User with access to this company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Company",
                "verbose_name_plural": "User Companies",
                "db_table": "common_user_companies",
                "unique_together": {("user", "company")},
            },
        ),
        migrations.CreateModel(
            name="UserBranch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Whether this is the user's default branch"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time when user was assigned to this branch"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch that the user has access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_branches",
                        to="common.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User with access to this branch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_branches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Branch",
                "verbose_name_plural": "User Branches",
                "db_table": "common_user_branches",
                "unique_together": {("user", "branch")},
            },
        ),
    ]
