# Generated by Django 4.2.20 on 2026-06-30 11:58

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Whether this record has been soft deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Date and time when record was deleted", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the user",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(help_text="Full name of the user", max_length=255)),
                ("email", models.EmailField(help_text="Email address of the user", max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number with country code",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: +999999999. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Designates whether this user should be treated as active."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Designates whether the user can log into this admin site."
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when user was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date and time when user was last updated"),
                ),
                ("last_login", models.DateTimeField(blank=True, help_text="Date and time of last login", null=True)),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(blank=True, help_text="Date and time when email was verified", null=True),
                ),
                (
                    "email_verification_attempts",
                    models.IntegerField(default=0, help_text="Number of verification attempts"),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(default=0, help_text="Number of consecutive failed login attempts"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, help_text="Date and time until the account is locked", null=True),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time of last password change"),
                ),
                (
                    "is_2fa_enabled",
                    models.BooleanField(default=False, help_text="Whether two-factor authentication is enabled"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the role",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Role name (matches group name)", max_length=150, unique=True)),
                ("description", models.TextField(blank=True, help_text="Description of the role and its permissions")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Whether this is a system role that cannot be deleted"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when role was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date and time when role was last updated"),
                ),
                (
                    "group",
                    models.OneToOneField(
                        help_text="Linked Django group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "auth_roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the session",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, help_text="Django session key", max_length=40, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when session was created"),
                ),
                ("expires_at", models.DateTimeField(help_text="Date and time when session expires")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address from which session was created", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent from which session was created")),
                ("browser", models.CharField(blank=True, help_text="Browser name and version", max_length=100)),
                (
                    "device",
                    models.CharField(blank=True, help_text="Device type (desktop, mobile, tablet)", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this session is still active")),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, help_text="Date and time of last activity in this session"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "auth_user_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the profile",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, help_text="Profile picture/avatar", null=True, upload_to="avatars/"),
                ),
                ("date_of_birth", models.DateField(blank=True, help_text="Date of birth", null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        help_text="Gender",
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(blank=True, help_text="Nationality", max_length=100)),
                ("department", models.CharField(blank=True, help_text="Department/Division", max_length=100)),
                ("job_title", models.CharField(blank=True, help_text="Job title", max_length=100)),
                ("employee_id", models.CharField(blank=True, help_text="Employee ID", max_length=50)),
                ("hire_date", models.DateField(blank=True, help_text="Date of hire", null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English"), ("fr", "Français")],
                        default="en",
                        help_text="Preferred language",
                        max_length=2,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("system", "System Default")],
                        default="system",
                        help_text="Preferred theme",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="Africa/Cairo", help_text="Preferred timezone", max_length=50)),
                ("email_notifications", models.BooleanField(default=True, help_text="Receive email notifications")),
                ("push_notifications", models.BooleanField(default=True, help_text="Receive push notifications")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when profile was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date and time when profile was last updated"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct manager/supervisor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User associated with this profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "auth_user_profiles",
            },
        ),
        migrations.CreateModel(
            name="PermissionCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Accounting, Inventory, Sales)", max_length=100, unique=True
                    ),
                ),
                ("code", models.CharField(help_text="Unique category code", max_length=50, unique=True)),
                ("description", models.TextField(blank=True, help_text="Category description")),
                ("icon", models.CharField(blank=True, help_text="CSS icon class", max_length=50)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_system", models.BooleanField(default=False, help_text="Whether this is a system category")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="authentication.permissioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Category",
                "verbose_name_plural": "Permission Categories",
                "db_table": "auth_permission_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the token",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, help_text="Hashed token for password reset", max_length=64, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when token was created"),
                ),
                ("expires_at", models.DateTimeField(help_text="Date and time when token expires")),
                ("is_used", models.BooleanField(default=False, help_text="Whether this token has been used")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address from which reset was requested", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent from which reset was requested")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting password reset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "auth_password_reset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the audit record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(help_text="Username used for login attempt", max_length=150)),
                ("login_time", models.DateTimeField(auto_now_add=True, help_text="Date and time of login attempt")),
                ("logout_time", models.DateTimeField(blank=True, help_text="Date and time of logout", null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the client", null=True),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string from the client")),
                ("browser", models.CharField(blank=True, help_text="Browser name and version", max_length=100)),
                (
                    "device",
                    models.CharField(blank=True, help_text="Device type (desktop, mobile, tablet)", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure"), ("locked", "Account Locked")],
                        default="success",
                        help_text="Status of the login attempt",
                        max_length=10,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, help_text="Reason for failure if any", max_length=255)),
                (
                    "session_key",
                    models.CharField(blank=True, help_text="Session key associated with this login", max_length=40),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who attempted to login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Audit",
                "verbose_name_plural": "Login Audits",
                "db_table": "auth_login_audit",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="EnterprisePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("admin", "Administrate"),
                            ("full", "Full Access"),
                        ],
                        default="view",
                        help_text="Type of permission",
                        max_length=20,
                    ),
                ),
                (
                    "is_enterprise",
                    models.BooleanField(default=True, help_text="Whether this is an enterprise permission"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Whether this is a system permission that cannot be deleted"
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Detailed description of the permission")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Permission category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions",
                        to="authentication.permissioncategory",
                    ),
                ),
                (
                    "django_permission",
                    models.OneToOneField(
                        help_text="Linked Django permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_permission",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enterprise Permission",
                "verbose_name_plural": "Enterprise Permissions",
                "db_table": "auth_enterprise_permissions",
                "ordering": ["category__order", "django_permission__codename"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the verification",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, help_text="Hashed token for email verification", max_length=64, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when token was created"),
                ),
                ("expires_at", models.DateTimeField(help_text="Date and time when token expires")),
                ("is_verified", models.BooleanField(default=False, help_text="Whether the email has been verified")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address from which verification was requested", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent from which verification was requested"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose email is being verified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "db_table": "auth_email_verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleEnterprisePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enterprise_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_roles",
                        to="authentication.enterprisepermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_permissions",
                        to="authentication.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Enterprise Permission",
                "verbose_name_plural": "Role Enterprise Permissions",
                "db_table": "auth_role_enterprise_permissions",
                "unique_together": {("role", "enterprise_permission")},
            },
        ),
    ]
